name: Build Android APK

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # Specify your Java version

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
